import type { Metadata } from 'next'
import './globals.css'
import './layout.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body id='layout-main'>{children}</body>
    </html>
  )
}
